// cmd/detect.go
package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/eugene-lai/ai-kernel/internal/detectors"
	"github.com/spf13/cobra"
)

var detectCmd = &cobra.Command{
	Use:   "detect",
	Short: "Scan codebase and generate .ai/ overlay files",
	RunE:  runDetect,
}

func init() {
	rootCmd.AddCommand(detectCmd)
}

func runDetect(cmd *cobra.Command, args []string) error {
	dir, _ := os.Getwd()

	result := detectors.DetectResult{
		Platform:   detectors.DetectPlatform(dir),
		TestRunner: detectors.DetectTestRunner(dir),
		VerifyCmds: detectors.DetectVerifyCmds(dir),
		MCPTools:   detectors.DetectMCPTools(dir),
	}

	if err := writeExecutionOverlay(dir, result); err != nil {
		return fmt.Errorf("writing execution overlay: %w", err)
	}
	if err := writeToolOverrides(dir, result); err != nil {
		return fmt.Errorf("writing tool overrides: %w", err)
	}

	fmt.Printf("✓ Detected: platform=%s test_runner=%s verify_cmds=%d mcp_tools=%d\n",
		result.Platform, result.TestRunner, len(result.VerifyCmds), len(result.MCPTools))
	fmt.Println("✓ Generated: .ai/loops/execution.md, .ai/tool-overrides.md")
	fmt.Println("→ Review and adjust generated files before committing.")
	return nil
}

func writeExecutionOverlay(dir string, r detectors.DetectResult) error {
	path := filepath.Join(dir, ".ai", "loops", "execution.md")
	os.MkdirAll(filepath.Dir(path), 0755)

	browserTool := "agent-browser"
	if r.Platform == detectors.PlatformIOS {
		browserTool = "maestro"
	}

	verifyCmds := "# TODO: add verify commands"
	if len(r.VerifyCmds) > 0 {
		verifyCmds = strings.Join(r.VerifyCmds, "\n")
	}

	content := fmt.Sprintf(`# Execution Overlay
# Auto-generated by ai-kernel detect — review and adjust.

## Project Config

platform: %s
test_runner: %s
browser_tool: %s

## Verify Commands

%s

## Overrides
# Add any project-specific overrides to the base execution loop below.
# See .ai/base/loops/execution.md for the full base loop.
`, r.Platform, r.TestRunner, browserTool, verifyCmds)

	return os.WriteFile(path, []byte(content), 0644)
}

func writeToolOverrides(dir string, r detectors.DetectResult) error {
	path := filepath.Join(dir, ".ai", "tool-overrides.md")

	var lines []string
	lines = append(lines, "# Tool Overrides")
	lines = append(lines, "# Auto-generated by ai-kernel detect — add only divergences from base defaults.")
	lines = append(lines, "")

	if r.Platform == detectors.PlatformIOS {
		lines = append(lines, "## Replacements")
		lines = append(lines, "browser: maestro")
		lines = append(lines, "")
	}

	if len(r.MCPTools) > 0 {
		lines = append(lines, "## Detected MCP Servers")
		for _, t := range r.MCPTools {
			lines = append(lines, fmt.Sprintf("# %s: %s", t.Name, t.Command))
		}
	}

	return os.WriteFile(path, []byte(strings.Join(lines, "\n")+"\n"), 0644)
}
